# -*- coding: utf-8 -*-
"""Data Scientist - Sawit Pro

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vuERd1H6zGFemZe73QtDJebybKHExdZh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data-old.csv')

df.shape

df.head()

df.sample(5)

df.tail()

df.info()

df['date'] = pd.to_datetime(df['date'])

df.isnull().sum().head(37)*100/len(df)

df.isnull().sum().tail(31)*100/len(df)

fill = df.columns[df.dtypes != object].tolist()

for i in fill:
  df[i] = df[i].fillna(0)

"""#What is the probability of dying from COVID infection in France in March 2023 for a 25 year old?
Draw the relevant correlation projections

**Note :** In this case, I do not see any age column in this data. Thus, I am only looking for the probability of the death rate in France in March 2023.
"""

# probability here p = total new deaths / total new_cases

france = df[(df['location'] == 'France') & (df['date'].dt.year == 2023) & (df['date'].dt.month == 3)]
print("Probability dying from COVID : ", france['new_deaths'].sum()/france['new_cases'].sum())

"""#What is the correlation between the number of deaths with age for the US, China, France and Germany?

**Note :** In this case, I do not see any age column in this data. Thus, I am only looking for correlation between new cases and new vaccinations
"""

df[df['location'] == 'United States']['total_deaths'].dtypes

df[df['location'] == 'United States']['new_cases'].corr(df[df['location'] == 'United States']['new_vaccinations'])

# Correlation between number of deaths with Share of the population that is 65 years and older in US
Corr_US = df[df['location'] == 'United States']['new_cases'].corr(df[df['location'] == 'United States']['new_vaccinations'])
print('Correlation between number of cases with vaccinations in US: ', Corr_US)

# Correlation between number of deaths with Share of the population that is 65 years and older in China
Corr_CHN = df[df['location'] == 'China']['new_cases'].corr(df[df['location'] == 'China']['new_vaccinations'])
print('Correlation between number of cases with vaccinations in China: ', Corr_CHN)

# Correlation between number of deaths with Share of the population that is 65 years and older in France
Corr_FR = df[df['location'] == 'France']['new_cases'].corr(df[df['location'] == 'France']['new_vaccinations'])
print('Correlation between number of cases with vaccinations in France: ', Corr_FR)

# Correlation between number of deaths with Share of the population that is 65 years and older in Germany
Corr_GRMN = df[df['location'] == 'Germany']['new_cases'].corr(df[df['location'] == 'Germany']['new_vaccinations'])
print('Correlation between number of cases with vaccinations in Germany: ', Corr_GRMN)

"""This value maybe lower caused the Covid cases start around 2019 and 2020, while the vaccinations start around last 2020. So there's 11 month data not filled in the column new_vaccinations"""